### ISSUE TITLE
Include of non-modular header inside in Xcode7.1 with Carthage

### ISSUE THREAD

**Issue by jakecraige** [ReactiveCocoa/ReactiveCocoa#2557]
This issue is the same error described in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2495 except it's happening with Carthage.

Error output:

```sh
RACExample[example-app*] $ carthage update --platform iOS
*** Fetching RACExample
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out RACExample at "3acc6eb4987fadc17042d29e9c0fe7e967e8b222"
*** Checking out Result at "0.6.0-beta.5"
*** Downloading ReactiveCocoa.framework binary at "v4.0-alpha.3"
*** xcodebuild output can be found in /var/folders/vb/jz3wqx8153vcdhm6dqmd99d80000gn/T/carthage-xcodebuild.mzEvVg.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "RGB" in RGB.xcworkspace
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:68:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:69:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:70:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:71:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:72:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:73:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:74:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:75:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:76:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:77:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:78:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:79:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:80:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:81:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:82:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:83:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:84:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
/tmp/RACExample/Carthage/Checkouts/RACExample/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:85:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
<unknown>:0: error: too many errors emitted, stopping now
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

How I produced this:

1. Create a framework that uses Carthage as a dependency manager
1. Add ReactiveCocoa as a dependency of that framework
1. Add the framework to a separate project as a dependency and try to build

I've created a repo and framework for you to use that reproduces this error here: https://github.com/jakecraige/RACExample

Let me know if there's anything I can do to help.

**Comment by JaviLorbada** [comment]
Does anyone know how to solve / work around this issue? 🙏

**Comment by mdiep** [comment]
Can you post an example `Cartfile` that reproduces the issue?

**Comment by JaviLorbada** [comment]
Like @jakecraige has explained, the issue is reproducible when a framework uses Carthage as a dependancy manager and has ReactiveCocoa as a dependancy. Then try to link the framework to new project as a dependancy.

[Cartfile](https://github.com/jakecraige/RACExample/blob/example-app/Cartfile) that uses the example project: https://github.com/jakecraige/RACExample.

If more information is needed I can try to create another framework and project to reproduce it.

**Comment by mdiep** [comment]
I took a look that repo, but couldn't understand the instructions. Using a `file:///` repo in the Cartfile complicates things considerably.

**Comment by JaviLorbada** [comment]
@mdiep thanks for taking the time! 😊

I just created a framework that has RAC as a dependancy (https://github.com/JaviLorbada/RGB)

And then I use the following Cartfile in any project:

```
github "JaviLorbada/RGB" "1.0.0"
```

You can reproduce the issue in this project (https://github.com/JaviLorbada/RACExample)

**Comment by mdiep** [comment]
Well… I'm really confused. I can reproduce the issue, but I don't understand what's causing it.

Carthage is running this command:

```
/usr/bin/xcrun xcodebuild -workspace Carthage/Checkouts/RGB/RGB.xcworkspace -scheme RGB -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= clean build
```

For the implicit dependencies in `RGB.xcworkspace`, Xcode builds ReactiveCocoa. But it seems to be building for watchOS and tvOS with the files from iOS or something like that:

```
CompileSwift normal arm64
    cd /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa
    /Applications/Xcode7.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -emit-bc /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Optional.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Disposable.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Errors.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/ObjectiveCBridging.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Scheduler.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Action.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Atomic.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Bag.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/TupleExtensions.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/FoundationExtensions.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Flatten.swift /Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Observer.swift -target arm64-apple-ios8.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode7.1.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -I /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Products/Release-iphoneos -F /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Products/Release-iphoneos -application-extension -g -import-underlying-module -module-cache-path /Users/mdiep/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/ReactiveCocoa-generated-files.hmap -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/ReactiveCocoa-own-target-headers.hmap -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/ReactiveCocoa-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/ReactiveCocoa-project-headers.hmap -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Products/Release-iphoneos/include -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/DerivedSources/arm64 -Xcc -I/Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/DerivedSources -Xcc -DNDEBUG=1 -Xcc -DDTRACE_PROBES_DISABLED=1 -Xcc -ivfsoverlay -Xcc /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa -emit-module-doc-path /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/ReactiveCocoa.swiftdoc -O -module-name ReactiveCocoa -emit-module-path /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/ReactiveCocoa.swiftmodule -emit-objc-header-path /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/ReactiveCocoa-Swift.h -serialize-diagnostics-path /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Optional.dia -emit-dependencies-path /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Optional.d -num-threads 4 -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Optional.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Disposable.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Errors.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Event.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/ObjectiveCBridging.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Scheduler.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Action.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Property.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Signal.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/SignalProducer.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Atomic.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Bag.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/TupleExtensions.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/FoundationExtensions.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Flatten.bc -o /Users/mdiep/Library/Developer/Xcode/DerivedData/RGB-fimdludicnndbbcgicvkwtnbsmvn/Build/Intermediates/ReactiveCocoa.build/Release-iphoneos/ReactiveCocoa-watchOS.build/Objects-normal/arm64/Observer.bc
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h"
        ^
/Users/mdiep/Downloads/tmp/Carthage/Checkouts/RGB/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: include of non-modular header inside framework module 'ReactiveCocoa'
        #import <ReactiveCocoa/MKAnnotationView+RACSignalSupport.h>
                ^
```

The complains all seem to be about iOS extensions. :confused:

**Comment by JaviLorbada** [comment]
I've noticed the same about the `tvOS`, and no idea why that's happening. I don't know if this needs further investigation 😉

I did work around the issue by creating the framework in a different way. Basically I don't add the frameworks to the `.xcworkspace`.

**Comment by ReDetection** [comment]
This should be fixed by upgrading to Xcode 7.2, no?

**Comment by JaviLorbada** [comment]
Running Xcode 7.2 here:

Information running `xcodebuild -showBuildSettings`

```
    XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
    XCODE_PRODUCT_BUILD_VERSION = 7C68
    XCODE_VERSION_ACTUAL = 0720
    XCODE_VERSION_MAJOR = 0700
    XCODE_VERSION_MINOR = 0720
```

Do you mean Xcode 7.3? I have not tried that yet.

**Comment by ReDetection** [comment]
No, I meant 7.2. I see `/Applications/Xcode7.1.1.app/` above in the in the comment of @mdiep, I saw this issue in 7.1 and it's gone today when I updated it to 7.2

**Comment by JaviLorbada** [comment]
I did not realise about that 😅, I still get this issue with Xcode 7.2 tough 🤔

**Comment by adgarcia** [comment]
I've been having the exact same (extremely frustrating!) issue. The only thing that's worked has been to checkout my dependencies ('carthage update --no-build'), manually add a module map for ReactiveCocoa, restart Xcode, and then run 'carthage build'. 

It's ridiculous.

**Comment by mdiep** [comment]
I _think_ that Xcode is getting confused by the different versions of `ReactiveCocoa.framework` and using the wrong `modulemap` when building via implicit dependencies in a workspace.

**Comment by mdiep** [comment]
I was able to work around this by turning of _Find Implicit Dependencies_ and _Parallelize Build_ in my project's iOS scheme and adding the dependencies (including RAC) as explicit dependencies.

**Comment by adgarcia** [comment]
@mdiep That seems to solve things; thanks for the work around!
