### ISSUE TITLE
Can't build on Xcode 7.3.1

### ISSUE THREAD

**Issue by gabro** [ReactiveCocoa/ReactiveCocoa#2973]
I installed ReactiveCocoa using Carthage on Xcode 7.3.1 and this is the error I get

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ReactiveCocoa.h"
        ^
/<path/to/project>/Carthage/Build/iOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h:17:9: error: 'ReactiveCocoa/EXTKeyPathCoding.h' file not found
#import <ReactiveCocoa/EXTKeyPathCoding.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

I checked the Framework Search Path, but it correctly includes `$(PROJECT_DIR)/Carthage/Build/iOS`.

Incidentally that's the same error I get if I try to install it using CocoaPods.

Any hint of why that may be happening?

**Comment by mdiep** [comment]
What version of ReactiveCocoa?

> ```
> <module-includes>:1:9: note: in file included from <module-includes>:1:
> #import "Headers/ReactiveCocoa.h"
> ```

I don't know why it would be, but maybe things are upset because you're not using a framework import for RAC? (`#import <ReactiveCocoa/ReactiveCocoa.h>`)

**Comment by jondkimball** [comment]
I just started getting that same error. ReactiveCocoa 4.1.0 Xcode 7.3.1 cocoapods 1.0.1. The error started after upgrading to cocoapods 1.0.1 but still occurs even if I roll back to 0.39.0

 ```
<module-includes>:1:9:

 note: in file included from <module-includes>:1:
#import "Headers/ReactiveCocoa-umbrella.h"
        ^
.../Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-umbrella.h:18:9: note: in file included from .../Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-umbrella.h:18:
#import "NSObject+RACPropertySubscribing.h"
        ^
.../Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/NSObject+RACPropertySubscribing.h:10:9: error: 'ReactiveCocoa/EXTKeyPathCoding.h' file not found
#import <ReactiveCocoa/EXTKeyPathCoding.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

**Comment by mdiep** [comment]
I believe that's a problem with the podspec (#2909).

@gabro Maybe you're still picking up a copy of ReactiveCocoa that was built with CocoaPods somehow?

**Comment by gabro** [comment]
@mdiep yes, it looks like it was a leftover from a previous installation using CocoaPods v0.96

I solved the issue performing a "Clean Build Folder..." action (under the `Product` menu, holding down the option key).

After that, I managed to use ReactiveCocoa both with CocoaPods 1.0.1 and Carthage.

Thanks for the support!

**Comment by PlayBoyPlum** [comment]
hello ,i am meet the same problem with yours. but mine is in OC project. 
I use cocoaPods to access the RAC 4.2.2
/Users/plum/Desktop/RAC/RAC/Objective-C/RACTuple.m:10:9: 'ReactiveCocoa/EXTKeyPathCoding.h' file not found
