### ISSUE TITLE
Can´t build after updating Cocoapods to 1.0.1

### ISSUE THREAD

**Issue by AleLudovici** [ReactiveCocoa/ReactiveCocoa#2997]
After updating Cocoapods I am getting the following error:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ReactiveCocoa-umbrella.h"
        ^
/Users/alessandro/Development/NTS/Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-umbrella.h:18:9: note: in file included from /Users/alessandro/Development/NTS/Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/ReactiveCocoa-umbrella.h:18:
#import "NSObject+RACPropertySubscribing.h"
        ^
/Users/alessandro/Development/NTS/Build/Products/Debug-iphonesimulator/ReactiveCocoa/ReactiveCocoa.framework/Headers/NSObject+RACPropertySubscribing.h:10:9: error: 'ReactiveCocoa/EXTKeyPathCoding.h' file not found
#import <ReactiveCocoa/EXTKeyPathCoding.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```
I'm importing the framework in Swift with `import ReactiveCocoa`
Cleaning the build folder as suggested in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2973 does not work me. The problem persist after reinstalling from scratch both cocoapods and ReactiveCocoa.

**Comment by AleLudovici** [comment]
Issue solved. For those experiencing the same problem, please make sure to delete manually the Build folder` rm -rd Build/` after upgrading to cocoa pods 1.0.1

**Comment by PlayBoyPlum** [comment]
which dir can i excute the  command?
